// Server-only loader for Boris IR artifacts (manifest.json, graph.json).
//
// These files are GENERATED by Boris (see boris-data.sh) into data/. SvelteKit
// reads them once at build time during prerendering; the published site is
// fully static. Import this only from +page.server.ts / +layout.server.ts —
// node:fs must never reach the client bundle.
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Graph, Manifest } from './types';

export const DATA_DIR = join(process.cwd(), 'data');

async function readJson<T>(rel: string): Promise<T> {
	try {
		return JSON.parse(await readFile(join(DATA_DIR, rel), 'utf8')) as T;
	} catch (e) {
		// Fail the build loudly: missing Boris output is not a 404, it is a
		// broken consumer pipeline.
		throw new Error(`Cannot read generated Boris artifact data/${rel} (${String(e)}). Run \`npm run data\` (boris-data.sh) first.`);
	}
}

export function loadManifest(): Promise<Manifest> {
	return readJson<Manifest>('manifest.json');
}

export function loadGraph(): Promise<Graph> {
	return readJson<Graph>('graph.json');
}
