//! Standalone reproducer for drawmeanelephant/boris#420:
//! "Touch Atlas streaming checks parse is byte-offset sensitive: identical
//! 216-finding report passes at one file length, fails at finding #207 at
//! another."
//!
//! Mechanism (root cause):
//!   `writeAfterClaims` streams the committed checks report through
//!   `EvidenceInput.pass2_buffer` — a fixed 64 KiB chunk — and hands the
//!   stream to `std.json.Reader`. When a JSON string VALUE straddles a 64 KiB
//!   chunk boundary, the scanner cannot complete the token and surfaces it as
//!   a `.partial_string` token. `skipJsonValue` in src/publication_touches.zig
//!   (boris @ 30805ab8) treats that partial token as a complete value and
//!   returns, leaving the scanner mid-string. The next key read then consumes
//!   the remainder of the string as a key token, which fails the finding
//!   schema -> `error.InvalidChecksReport`.
//!
//!   Whether any token straddles a boundary is a pure function of the file's
//!   byte length, which is why a 218-byte-shorter report (the "public" target
//!   form) fails while the identical content under the "default" target
//!   parses cleanly (boris#417). Inside an object-skip, `.partial_string`
//!   tokens are harmless (the depth loop just reads the next token), which is
//!   why only bare-string values skipped via `skipJsonValue` — e.g. a
//!   finding's `owner` — trigger it.
//!
//! This harness synthesizes a schema-valid 216-finding checks report, pads it
//! so that finding #207's `"owner":"publication"` value straddles the 64 KiB
//! boundary, and drives the REAL `parseChecksStream` through the same 64 KiB
//! streaming reader `writeAfterClaims` uses. The identical report padded by
//! exactly 13 bytes more (no straddle) parses all 216 findings.

const std = @import("std");
const builtin = @import("builtin");
const publication_touches = @import("publication_touches");

const Io = std.Io;

const expected_target = "public";
const finding_count = 216;
const finding_index = 207; // 0-based: the 208th finding
const boundary_bytes = 64 * 1024;
const work_subdir = "repro-420-io";
const checks_file = "repro-420-io/checks.json";

// Preamble of the committed checks report (format / schema_version / target /
// artifact_inventory / checks[3]) generated by boris 30805ab8 itself. Its
// checks record finding counts [0, 0, 216], so the schema-validating tail of
// parseChecksStream (finding_offset chaining + last_end == findings.len)
// agrees exactly with the 216 findings generated below. Bytes 0..2241 of the
// real checks.json — the `"findings": [` opener is included.
const preamble =
    "{\n  \"format\": \"boris-publication-checks\",\n  \"schema_version\": 1,\n  \"target\": \"public\",\n  \"artifact_inventory\": {\n    \"path\": \"_boris/proof/artifacts.json\",\n    \"bytes\": 11840,\n    \"sha256\": \"ac5ef4252a00b30b0f06cee65d07c24c171ef3117389a6151dde208dc78194f3\",\n    \"format\": \"boris-publication-artifacts\",\n    \"schema_version\": 1,\n    \"target\": \"public\",\n    \"artifact_count\": 39\n  },\n  \"checks\": [\n    {\n      \"id\": \"artifact-integrity\",\n      \"eligible\": true,\n      \"ran\": true,\n      \"status\": \"passed\",\n      \"coverage\": \"complete\",\n      \"scope\": {\n        \"subject_statuses\": [\"committed\"],\n        \"subject_kinds\": [],\n        \"subject_sha256\": \"68a3191bdc5ae6ebb4931e2108efa916721edf61225d3559a679066cff1276b2\",\n        \"supporting_statuses\": [],\n        \"supporting_kinds\": [],\n        \"supporting_sha256\": \"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\"\n      },\n      \"counts\": {\"eligible\": 39, \"checked\": 39, \"findings\": 0},\n      \"finding_offset\": 0\n    },\n    {\n      \"id\": \"rendered-html\",\n      \"eligible\": true,\n      \"ran\": true,\n      \"status\": \"passed\",\n      \"coverage\": \"complete\",\n      \"scope\": {\n        \"subject_statuses\": [\"committed\"],\n        \"subject_kinds\": [\"html-page\"],\n        \"subject_sha256\": \"a427ccd6e427b14cb183ed61da84b0471aa9f37d1dba53e5533bf632ed67d10e\",\n        \"supporting_statuses\": [\"committed\"],\n        \"supporting_kinds\": [],\n        \"supporting_sha256\": \"68a3191bdc5ae6ebb4931e2108efa916721edf61225d3559a679066cff1276b2\"\n      },\n      \"counts\": {\"eligible\": 36, \"checked\": 36, \"findings\": 0},\n      \"finding_offset\": 0\n    },\n    {\n      \"id\": \"rendered-search\",\n      \"eligible\": true,\n      \"ran\": true,\n      \"status\": \"failed\",\n      \"coverage\": \"complete\",\n      \"scope\": {\n        \"subject_statuses\": [\"committed\"],\n        \"subject_kinds\": [\"rendered-search\"],\n        \"subject_sha256\": \"994fdf17774d76af6283a2c94ca18a16773a4fd3b0d10feb5d616e857fe27e33\",\n        \"supporting_statuses\": [\"committed\"],\n        \"supporting_kinds\": [\"html-page\"],\n        \"supporting_sha256\": \"a427ccd6e427b14cb183ed61da84b0471aa9f37d1dba53e5533bf632ed67d10e\"\n      },\n      \"counts\": {\"eligible\": 1, \"checked\": 1, \"findings\": 216},\n      \"finding_offset\": 0\n    }\n  ],\n  \"findings\": [";

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const gpa = arena.allocator();

    std.debug.print("repro-420: Touch Atlas streaming checks parse (boris checked-out src, zig {s})\n", .{builtin.zig_version_string});
    std.debug.print("  generating a schema-valid {d}-finding checks report; expected target {s}\n", .{ finding_count, expected_target });

    // 1) Un-padded report: locate finding #207's `"owner":"publication"` value.
    const base = try buildReport(gpa, 0);
    const owner_key_off = nthOccurrence(base, "\"owner\":\"publication\"", finding_index);
    const owner_val_off = owner_key_off + "\"owner\":".len;
    std.debug.print("  un-padded: finding #{d} owner value token at byte {d} (mod 65536 = {d})\n", .{ finding_index, owner_val_off, owner_val_off % boundary_bytes });
    if (owner_val_off >= boundary_bytes - 14 or owner_val_off < boundary_bytes - 65536)
        return error.UnsuitableLayout;

    // 2) Padding: fail case puts the 64 KiB boundary 6 bytes into the owner
    //    token (which is 13 bytes: quote + "publication" + quote); the control
    //    is the same report 13 bytes longer, so the token sits entirely above
    //    the boundary.
    const pad_fail = boundary_bytes - owner_val_off - 6;
    const pad_pass = pad_fail + 13;
    const report_fail = try buildReport(gpa, pad_fail);
    const report_pass = try buildReport(gpa, pad_pass);

    std.debug.print("  padding: {d} bytes (failing) / {d} bytes (control)\n", .{ pad_fail, pad_pass });
    std.debug.print("  FAILING report: {d} bytes; owner token spans {d}..{d} -> straddles {d}\n", .{ report_fail.len, owner_val_off + pad_fail, owner_val_off + pad_fail + 13, boundary_bytes });
    std.debug.print("  CONTROL report: {d} bytes; owner token spans {d}..{d} -> no straddle\n", .{ report_pass.len, owner_val_off + pad_pass, owner_val_off + pad_pass + 13 });

    Io.Dir.cwd().createDirPath(io, work_subdir) catch |err| {
        std.debug.print("  !! cannot create temp dir: {s}\n", .{@errorName(err)});
        return err;
    };
    defer Io.Dir.cwd().deleteTree(io, work_subdir) catch {};

    // 3) The failing case: expect parseChecksStream to die.
    const fail_result: ?usize = runParse(io, gpa, report_fail, "failing") catch |err| switch (err) {
        error.ParseFailed => blk: {
            std.debug.print("  => REPRODUCED: parseChecksStream returned error.InvalidChecksReport on the {d}-byte report\n", .{report_fail.len});
            std.debug.print("     (finding #{d}'s skipped `owner` value straddles the 64 KiB chunk boundary)\n", .{finding_index});
            break :blk null;
        },
        else => return err,
    };

    // 4) The control: the same content, 13 bytes longer, must parse everything.
    const parsed_count = try runParse(io, gpa, report_pass, "control");
    if (parsed_count != finding_count) {
        std.debug.print("  !! control parsed {d} findings, expected {d}\n", .{ parsed_count, finding_count });
        return error.ReproFailed;
    }

    if (fail_result != null) {
        std.debug.print("  !! failing report parsed cleanly — repro did NOT reproduce\n", .{});
        return error.ReproFailed;
    }

    std.debug.print("\nRESULT: REPRODUCED — a {d}-byte checks report dies at finding #{d};\n", .{ report_fail.len, finding_index });
    std.debug.print("        the identical report at {d} bytes parses all {d} findings.\n", .{ report_pass.len, finding_count });
}

fn buildReport(gpa: std.mem.Allocator, pad: usize) ![]u8 {
    var out = std.ArrayList(u8).empty;
    errdefer out.deinit(gpa);
    try out.appendNTimes(gpa, ' ', pad);
    try out.appendSlice(gpa, preamble);
    for (0..finding_count) |i| {
        if (i != 0) try out.appendSlice(gpa, ",\n    ");
        try appendFinding(gpa, &out, i);
    }
    try out.appendSlice(gpa, "\n  ]\n}\n");
    return out.toOwnedSlice(gpa);
}

fn appendFinding(gpa: std.mem.Allocator, out: *std.ArrayList(u8), index: usize) !void {
    try out.appendSlice(gpa, "{\"code\":\"SEARCH_CONTENT_MISMATCH\",\"domain\":\"artifact\",\"severity\":\"error\",\"confidence\":\"certain\",\"owner\":\"publication\",\"subject\":{\"kind\":\"artifact\",\"id\":\"docs/page-");
    var id_buf: [64]u8 = undefined;
    const id = try std.fmt.bufPrint(&id_buf, "{d:0>3}", .{index});
    try out.appendSlice(gpa, id);
    try out.appendSlice(gpa, ".md\",\"target\":\"public\"},\"remediation\":\"");
    try out.appendNTimes(gpa, 'R', 56);
    try out.appendSlice(gpa, "\",\"fixability\":\"regenerate\"}");
}

/// Run the REAL parseChecksStream over `bytes`, streamed through a 64 KiB
/// reader exactly as writeAfterClaims does for the checks report.
fn runParse(io: Io, gpa: std.mem.Allocator, bytes: []const u8, label: []const u8) !usize {
    Io.Dir.cwd().writeFile(io, .{ .sub_path = checks_file, .data = bytes }) catch |err| {
        std.debug.print("  !! cannot write {s}: {s}\n", .{ checks_file, @errorName(err) });
        return err;
    };

    const file = try Io.Dir.cwd().openFile(io, checks_file, .{});
    defer file.close(io);
    var buffer: [boundary_bytes]u8 = undefined;
    var stream = file.readerStreaming(io, &buffer);

    const parsed = publication_touches.parseChecksStream(gpa, &stream.interface, expected_target) catch |err| {
        std.debug.print("  [{s}] parseChecksStream FAILED: {s}\n", .{ label, @errorName(err) });
        if (@errorReturnTrace()) |trace| std.debug.dumpErrorReturnTrace(trace);
        return error.ParseFailed;
    };
    std.debug.print("  [{s}] parseChecksStream parsed {d} findings\n", .{ label, parsed.findings.len });
    return parsed.findings.len;
}

fn nthOccurrence(haystack: []const u8, needle: []const u8, n: usize) usize {
    var idx: usize = 0;
    var seen: usize = 0;
    while (std.mem.indexOfPos(u8, haystack, idx, needle)) |pos| {
        if (seen == n) return pos;
        seen += 1;
        idx = pos + needle.len;
    }
    unreachable;
}
